import type { Metadata } from "next";
import Link from "next/link";
import { Brain, BookOpen, Zap, Trophy, ArrowRight, Sparkles } from "lucide-react";
import { auth } from "@bitebase/api";
import { headers, cookies } from "next/headers";
import LandingNav from "@/components/landing-nav";
import { JsonLd } from "@/components/json-ld";

export const metadata: Metadata = {
  title: "BiteBase — Personalized Learning, Built by AI",
  description:
    "Tell BiteBase what you want to learn. Get a personalized course with lessons and quizzes, generated just for you.",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "BiteBase — Personalized Learning, Built by AI",
    description:
      "Tell BiteBase what you want to learn. Get a personalized course with lessons and quizzes, generated just for you.",
  },
  // FAQPage structured data for AI answer engines — served via metadata
  // so it doesn't require inline scripts (CSP-safe).
  other: {
    "script-type-ld+json-faq": JSON.stringify({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "What is BiteBase?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "BiteBase is an AI-powered learning app that generates personalized courses with lessons and quizzes. You tell it what you want to learn, and it creates a step-by-step course tailored to your experience level and goals.",
          },
        },
        {
          "@type": "Question",
          name: "How does BiteBase work?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Chat with BiteBase about what you want to learn. Answer a few questions about your experience and goals. BiteBase generates a structured course with bite-sized lessons and quizzes. You unlock lessons sequentially by passing each quiz.",
          },
        },
        {
          "@type": "Question",
          name: "Is BiteBase free?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, BiteBase is free to use. Your learning progress and courses are securely stored in your account, while the AI generates content tailored specifically to you.",
          },
        },
        {
          "@type": "Question",
          name: "What can I learn with BiteBase?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Anything! Pick any topic — programming, languages, history, science, art, business — and BiteBase will build a course around it with lessons and quizzes.",
          },
        },
        {
          "@type": "Question",
          name: "How are lessons generated?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Lessons are generated by AI based on your chosen topic, experience level, and goals. Each lesson includes real-world examples, clear explanations, and a quiz to reinforce what you've learned.",
          },
        },
      ],
    }),
  },
};


export const dynamic = "force-dynamic";

async function getSession() {
  if (process.env.NODE_ENV !== "production") {
    const cookieStore = await cookies();
    if (cookieStore.get("__playwright_test__")?.value === "1") {
      return true;
    }
  }
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    return !!session;
  } catch {
    return false;
  }
}

export default async function LandingPage() {
  const isLoggedIn = await getSession();
  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--color-bg-warm)' }}>
      <LandingNav isLoggedIn={isLoggedIn} />

      {/* WebApplication structured data */}
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "BiteBase",
          url: process.env.SITE_URL ?? "https://bitebase.labb.site",
          description:
            "Tell BiteBase what you want to learn, and it builds a personalized, quiz-filled course just for you.",
          applicationCategory: "EducationalApplication",
          operatingSystem: "Web",
          offers: {
            "@type": "Offer",
            price: "0",
            priceCurrency: "USD",
          },
          author: {
            "@type": "Person",
            name: "David Eriksson",
          },
        }}
      />
      <main>
        {/* ── Hero ────────────────────────────────────── */}
        <section className="relative overflow-hidden px-6 py-20 sm:py-28">
          {/* Subtle decorative background */}
          <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
            <div className="absolute -top-40 right-0 h-[600px] w-[600px] rounded-full opacity-[0.06]" style={{ backgroundColor: 'var(--color-accent)' }} />
            <div className="absolute -bottom-40 -left-40 h-[500px] w-[500px] rounded-full opacity-[0.05]" style={{ backgroundColor: 'var(--color-secondary)' }} />
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[800px] w-[800px] rounded-full opacity-[0.03]" style={{ background: 'radial-gradient(circle, var(--color-accent-subtle) 0%, transparent 70%)' }} />
          </div>
          <div className="mx-auto max-w-4xl text-center">
            <div
              className="mb-6 inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-sm font-medium"
              style={{
                borderColor: 'var(--color-accent-light)',
                backgroundColor: 'var(--color-accent-subtle)',
                color: 'var(--color-accent-dark)',
              }}
            >
              <Sparkles className="h-3.5 w-3.5" aria-hidden />
              AI-powered, personalized learning
            </div>
            <h1
              className="mb-6 font-[family-name:var(--font-fraunces)] text-4xl font-bold leading-tight tracking-tight sm:text-5xl lg:text-6xl text-balance"
              style={{ color: 'var(--color-text-primary)' }}
            >
              Learn anything.{" "}
              <span style={{ color: 'var(--color-accent)' }}>
                Bit by bit.
              </span>
            </h1>
            <p
              className="mx-auto mb-10 max-w-2xl text-lg leading-relaxed sm:text-xl"
              style={{ color: 'var(--color-text-muted)' }}
            >
              Tell BiteBase what you want to learn. Answer a few questions. Get a
              personalized course with lessons, real-world examples, and
              quizzes — all generated just for you.
            </p>
            <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Link
                href={isLoggedIn ? "/dashboard" : "/register"}
                className="bg-accent text-white inline-flex items-center gap-2 px-8 py-3.5 text-base font-semibold rounded-xl hover:bg-accent-dark"
              >
                {isLoggedIn ? "Go to dashboard" : "Start learning for free"}
                <ArrowRight className="h-4 w-4" />
              </Link>
              {!isLoggedIn && (
                <Link
                  href="/login"
                  className="btn-ghost inline-flex items-center gap-2 px-8 py-3.5 text-base font-semibold"
                >
                  Sign in
                </Link>
              )}
              <Link
                href="/explore"
                className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors flex items-center gap-1"
              >
                Explore community courses
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </div>
          </div>
        </section>



        {/* ── How it works (2+2 staggered) ───────────── */}
        <section className="mx-auto max-w-6xl px-6 pb-24">
          <div className="mb-12 text-center">
            <h2
              className="font-[family-name:var(--font-fraunces)] text-3xl font-bold sm:text-4xl"
              style={{ color: 'var(--color-text-primary)' }}
            >
              How it works
            </h2>
            <p className="mt-2" style={{ color: 'var(--color-text-muted)' }}>
              Four steps to your personalized course.
            </p>
          </div>
          <div className="space-y-8">
            {[
              {
                icon: Brain,
                title: "Tell us what you want to learn",
                desc: "Chat with BiteBase. It asks smart questions to understand your goals and level.",
                color: "accent",
              },
              {
                icon: BookOpen,
                title: "Get your course",
                desc: "BiteBase builds a structured, step-by-step learning plan tailored to your experience.",
                color: "secondary",
              },
              {
                icon: Zap,
                title: "Learn in bite-sizes",
                desc: "Short, focused lessons with real-world examples. No overwhelm — just steady progress.",
                color: "accent",
              },
              {
                icon: Trophy,
                title: "Test your knowledge",
                desc: "Quizzes after each lesson make sure the knowledge sticks. Pass to unlock the next one.",
                color: "secondary",
              },
            ].map((feature, i) => (
              <div
                key={feature.title}
                className="card card-hover flex flex-col items-start gap-4 p-6 sm:flex-row sm:items-center sm:gap-6 sm:p-8"
              >
                <div
                  className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl"
                  style={{
                    backgroundColor: feature.color === "accent"
                      ? 'var(--color-accent-subtle)'
                      : 'var(--color-secondary-subtle)',
                    color: feature.color === "accent"
                      ? 'var(--color-accent)'
                      : 'var(--color-secondary)',
                  }}
                >
                  <feature.icon className="h-7 w-7" aria-hidden />
                </div>
                <div className="flex-1">
                  <h3
                    className="mb-1 font-[family-name:var(--font-fraunces)] text-lg font-semibold"
                    style={{ color: 'var(--color-text-primary)' }}
                  >
                    {i + 1}. {feature.title}
                  </h3>
                  <p className="text-sm" style={{ color: 'var(--color-text-muted)' }}>
                    {feature.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
